server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
    password: admin
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
client:
  connectTimeout: 10000
  ms-weather-info:
    url: http://localhost:8080/weather/by
  readTimeout: 10000
